apiVersion: apps/v1
kind: Deployment
metadata:
  name: medical-image-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: medical-image-generator
  template:
    metadata:
      labels:
        app: medical-image-generator
    spec:
      containers:
      - name: api
        image: ghcr.io/mbadawi7/medical-image-generator:latest
        ports:
          - containerPort: 8000
        envFrom:
          - configMapRef:
              name: mig-config
        resources:
          requests:
            cpu: "0.5"
            memory: "512Mi"
          limits:
            cpu: "1"
            memory: "1Gi"
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
